### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by kukac7** [ascariandrea/revolut-sdk#13]
`Could not find module in path: 'revolut-sdk/dist/api/accounts' relative to '/node_modules/revolut-sdk/dist/index.js'`

[demo](https://codesandbox.io/embed/silly-neumann-sot12)

**Comment by ascariandrea** [comment]
I realised I didn't publish the package properly - try with the [v0.4.4](https://www.npmjs.com/package/revolut-sdk)

**Comment by kukac7** [comment]
cool, thanks!

but...

```
const accounts = revolut.accounts.getAll().run();
accounts.then(r => console.log(r)).catch(e => console.error(e));
```

`Left {value: Error, _tag: "Left", constructor: Object}`

**Comment by ascariandrea** [comment]
That's the correct result: `accounts` is [`Either`](https://gcanti.github.io/fp-ts/modules/Either.ts.html) type.
